name: apps:checkout

services:
  checkout:
    container_name: pj-esc-001831-apps-checkout
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV_USER=${DEV_USER:-developer}
    restart: on-failure
    tty: true
    volumes:
      - ../../:/workspace:cached
      - ${HOME}/.gitconfigure:/tmp/.gitconfigure:ro
      - ${HOME}/.ssh:/home/${DEV_USER:-developer}/.ssh
      - .devcontainer/.bashrc:/home/${DEV_USER:-developer}/.bashrc:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3050-3099:3000-3049'